[tool]
[tool.poetry]
name = "pytwoway"
version = "0.1.17"
description = "Estimate two way fixed effect labor models"
classifiers = ["Programming Language :: Python :: 3", "License :: OSI Approved :: MIT License", "Operating System :: OS Independent"]
homepage = "https://github.com/tlamadon/pytwoway"
authors = ["Thibaut Lamadon <thibaut.lamadon@gmail.com>"]
readme = "README.rst"

[tool.poetry.dependencies]
python = ">=3.6.1"
bipartitepandas = "*"
configargparse = "*"
matplotlib = "*"
numpy = "*"
pandas = ">=1.0"
pyamg = "*"
qpsolvers = "=1.6.1"
scipy = "*"
tqdm = "*"
